# Generated by Django 4.1.5 on 2023-02-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, max_length=255, verbose_name='Логин пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Пароль пользователя'),
        ),
    ]
