# Generated by Django 4.1.7 on 2023-04-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pagelink_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='boolprogress',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Страница пройдена'),
        ),
    ]
